class_name TrackVisuals
extends RefCounted
# Reference-video rail renderer. Everything here is generated by the game: a
# continuous dark roadbed, bright metal rails, sleepers and small fasteners.
# No external gameplay meshes are used.

const BASE_WIDTH := 0.92
const BED_WIDTH := 0.70
const RAIL_OFFSET := 0.36
const RAIL_WIDTH := 0.085
const SLEEPER_SPACING := 0.30
const BOLT_OFFSET := 0.30


static func create_path(parent: Node3D, points: PackedVector3Array, trim_start: float = 0.0, trim_end: float = 0.0) -> Node3D:
    var root := Node3D.new()
    root.name = "ReferenceRail"
    parent.add_child(root)

    var visible_points := _trim_path(points, trim_start, trim_end)
    if visible_points.size() < 2:
        return root

    _strip_layer(
        root, "Roadbed", visible_points, BASE_WIDTH, 0.12, 0.02, [0.0],
        VisualFactory.material(Color("#55585A"), 0.66, 0.0, 0.04)
    )
    _strip_layer(
        root, "InnerBed", visible_points, BED_WIDTH, 0.055, 0.105, [0.0],
        VisualFactory.material(Color("#343638"), 0.76)
    )
    _strip_layer(
        root, "Rails", visible_points, RAIL_WIDTH, 0.095, 0.215, [-RAIL_OFFSET, RAIL_OFFSET],
        VisualFactory.material(Color("#D7D4CC"), 0.24, 0.0, 0.34)
    )
    _sleeper_layer(root, visible_points)
    _bolt_layer(root, visible_points)
    return root


static func _trim_path(points: PackedVector3Array, trim_start: float, trim_end: float) -> PackedVector3Array:
    if points.size() < 2 or (trim_start <= 0.001 and trim_end <= 0.001):
        return points

    var total := TrackGeometry.length(points)
    var start_distance := clampf(trim_start, 0.0, total)
    var end_distance := clampf(total - trim_end, 0.0, total)
    if end_distance - start_distance < 0.18:
        return points

    var result := PackedVector3Array()
    var start_sample := TrackGeometry.sample_distance(points, start_distance)
    result.append(start_sample["position"] as Vector3)

    var walked := 0.0
    for i in range(1, points.size()):
        walked += points[i - 1].distance_to(points[i])
        if walked > start_distance + 0.01 and walked < end_distance - 0.01:
            result.append(points[i])

    var end_sample := TrackGeometry.sample_distance(points, end_distance)
    result.append(end_sample["position"] as Vector3)
    return result


static func _strip_layer(
    parent: Node3D,
    name_value: String,
    points: PackedVector3Array,
    width: float,
    height: float,
    y: float,
    laterals: Array,
    mat: Material
) -> void:
    if points.size() < 2:
        return

    var tool := SurfaceTool.new()
    tool.begin(Mesh.PRIMITIVE_TRIANGLES)
    tool.set_material(mat)
    for raw_lateral in laterals:
        _add_strip(tool, points, width, height, y, float(raw_lateral))
    tool.generate_normals()

    var instance := MeshInstance3D.new()
    instance.name = name_value
    instance.mesh = tool.commit()
    parent.add_child(instance)


static func _add_strip(tool: SurfaceTool, points: PackedVector3Array, width: float, height: float, y: float, lateral: float) -> void:
    var half_width := width * 0.5
    var half_height := height * 0.5
    var sections: Array[PackedVector3Array] = []
    for i in range(points.size()):
        var previous := points[maxi(0, i - 1)]
        var following := points[mini(points.size() - 1, i + 1)]
        var tangent := following - previous
        tangent.y = 0.0
        if tangent.length_squared() < 0.0001:
            tangent = Vector3.FORWARD
        tangent = tangent.normalized()
        var side := Vector3(tangent.z, 0.0, -tangent.x).normalized()
        var centre := points[i] + side * lateral + Vector3(0.0, y, 0.0)
        sections.append(PackedVector3Array([
            centre - side * half_width + Vector3.DOWN * half_height,
            centre + side * half_width + Vector3.DOWN * half_height,
            centre - side * half_width + Vector3.UP * half_height,
            centre + side * half_width + Vector3.UP * half_height,
        ]))

    for i in range(sections.size() - 1):
        var a := sections[i]
        var b := sections[i + 1]
        _add_quad(tool, a[2], b[2], b[3], a[3])
        _add_quad(tool, a[1], b[1], b[0], a[0])
        _add_quad(tool, a[0], b[0], b[2], a[2])
        _add_quad(tool, a[3], b[3], b[1], a[1])

    var first := sections[0]
    var last := sections[sections.size() - 1]
    _add_quad(tool, first[1], first[0], first[2], first[3])
    _add_quad(tool, last[0], last[1], last[3], last[2])


static func _add_quad(tool: SurfaceTool, a: Vector3, b: Vector3, c: Vector3, d: Vector3) -> void:
    for vertex in [a, b, c, a, c, d]:
        tool.add_vertex(vertex)


static func _sleeper_layer(parent: Node3D, points: PackedVector3Array) -> void:
    var total := TrackGeometry.length(points)
    var count := maxi(1, int(floor(total / SLEEPER_SPACING)))

    var mesh := BoxMesh.new()
    mesh.size = Vector3.ONE
    mesh.material = VisualFactory.material(Color("#737576"), 0.54, 0.0, 0.08)

    var multi := MultiMesh.new()
    multi.transform_format = MultiMesh.TRANSFORM_3D
    multi.mesh = mesh
    multi.instance_count = count

    for i in range(count):
        var distance := (float(i) + 0.5) * total / float(count)
        var sample := TrackGeometry.sample_distance(points, distance)
        var p: Vector3 = sample["position"]
        var tangent: Vector3 = sample["tangent"]
        var angle := atan2(tangent.x, tangent.z)
        var basis := Basis(Vector3.UP, angle).scaled(Vector3(0.78, 0.035, 0.075))
        multi.set_instance_transform(i, Transform3D(basis, p + Vector3(0, 0.175, 0)))

    var instance := MultiMeshInstance3D.new()
    instance.name = "Sleepers"
    instance.multimesh = multi
    parent.add_child(instance)


static func _bolt_layer(parent: Node3D, points: PackedVector3Array) -> void:
    var total := TrackGeometry.length(points)
    var sleeper_count := maxi(1, int(floor(total / SLEEPER_SPACING)))

    var mesh := CylinderMesh.new()
    mesh.top_radius = 0.035
    mesh.bottom_radius = 0.035
    mesh.height = 0.035
    mesh.radial_segments = 8
    mesh.material = VisualFactory.material(Color("#ECE8DF"), 0.22, 0.0, 0.40)

    var multi := MultiMesh.new()
    multi.transform_format = MultiMesh.TRANSFORM_3D
    multi.mesh = mesh
    multi.instance_count = sleeper_count * 2

    var index := 0
    for i in range(sleeper_count):
        var distance := (float(i) + 0.5) * total / float(sleeper_count)
        var sample := TrackGeometry.sample_distance(points, distance)
        var p: Vector3 = sample["position"]
        var tangent: Vector3 = sample["tangent"]
        var side := Vector3(tangent.z, 0.0, -tangent.x).normalized()
        for lateral in [-BOLT_OFFSET, BOLT_OFFSET]:
            multi.set_instance_transform(index, Transform3D(Basis.IDENTITY, p + side * float(lateral) + Vector3(0, 0.245, 0)))
            index += 1

    var instance := MultiMeshInstance3D.new()
    instance.name = "RailFasteners"
    instance.multimesh = multi
    parent.add_child(instance)
